# Use an OpenJDK base image
FROM openjdk:17-jdk

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR file
COPY target/Day27-Docker-WebClientBank-3.4.3.jar server-bank.jar

# Expose the Eureka Server port
EXPOSE 6061

# Run the application
ENTRYPOINT ["java", "-jar", "server-bank.jar"]
