# Use an OpenJDK base image
FROM openjdk:17-jdk

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR file
COPY target/Day27-Docker-WebClientCustomer-3.4.3.jar server-customer.jar

# Expose the Eureka Server port
EXPOSE 6060

# Run the application
ENTRYPOINT ["java", "-jar", "server-customer.jar"]
