# Use an OpenJDK base image
FROM openjdk:17-jdk

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR file
COPY target/Day27-Docker-WebClientVendor-3.4.3.jar server-vendor.jar

# Expose the Eureka Server port
EXPOSE 6062

# Run the application
ENTRYPOINT ["java", "-jar", "server-vendor.jar"]
