spring:
  application:
    name: server-registry

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
management:
  endpoints:
    web:
      exposure:
        include: "*"